apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-user0
  namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: user0
